name: Build

on:
  push:

concurrency:
  group: ci-build-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: pgxn/pgxn-tools
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build
        run: make

  docker:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: wideplink
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Docker meta
        uses: docker/metadata-action@v4
        id: meta
        with:
          images: ghcr.io/wideplink/pgencrypt
          flavor: latest=true
          tags: |
            type=sha
            type=sha,format=long

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha,mode=max
          cache-to: type=gha,mode=max
